name = "REPL"
defaultTargets = ["repl"]

[[lean_lib]]
name = "REPL"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.15.0"

[[require]]
name = "Cli"
scope = "leanprover"

[[require]]
name = "Socket"
git = "https://github.com/offendo/Socket.lean"
rev = "v4.15.0"

[[lean_exe]]
name = "repl"
root = "REPL"
supportInterpreter = true
